// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrnaquethuzvbsxcssss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybmFxdWV0aHV6dmJzeGNzc3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzA0NDYsImV4cCI6MjA2NzMwNjQ0Nn0.gGNkG0ck5DmKe9Xc5EVXWxDDTVheAz3WDz-Cot7A7eI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});